"""add idempotency_key to orders

Revision ID: 4a7b02995b0b
Revises: a327830a5b63
Create Date: 2026-09-17 20:25:09.530851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7b02995b0b'
down_revision: Union[str, None] = 'a327830a5b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index('uq_orders_buyer_idempotency_key', 'orders', ['buyer_id', 'idempotency_key'], unique=True, postgresql_where='idempotency_key IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_orders_buyer_idempotency_key', table_name='orders', postgresql_where='idempotency_key IS NOT NULL')
    op.drop_column('orders', 'idempotency_key')
    # ### end Alembic commands ###
