"""standardize timestamp columns to created_at, add named unique constraint on payments.order_id

Revision ID: a327830a5b63
Revises: 46520ed8368a
Create Date: 2026-09-16 22:05:24.080058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a327830a5b63'
down_revision: Union[str, None] = '46520ed8368a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_payments_order_id', 'payments', ['order_id'])
    op.add_column('payouts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('payouts', 'at')
    op.add_column('processed_events', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('processed_events', 'processed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_events', sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('processed_events', 'created_at')
    op.add_column('payouts', sa.Column('at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('payouts', 'created_at')
    op.drop_constraint('uq_payments_order_id', 'payments', type_='unique')
    # ### end Alembic commands ###
