"""add unit to pools

Revision ID: a6f89e9db827
Revises: 4a7b02995b0b
Create Date: 2026-09-18 09:41:15.949028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f89e9db827'
down_revision: Union[str, None] = '4a7b02995b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pools', sa.Column('unit', sa.String(length=50), server_default='unit', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pools', 'unit')
    # ### end Alembic commands ###
